development:
  adapter: postgresql
  encoding: unicode
  database: knowledge_overflow
  pool: 5
  username: postgres
  password: 
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: knowledge_overflow_test
  pool: 5
  username: postgres
  password: 
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: knowledge_overflow_production
  pool: 5
  username: postgres
  password: 
  host: localhost
  port: 5432
